### ISSUE TITLE
How can I change the size of the album art

### ISSUE THREAD

**Issue by finius04** [raywo/MMM-NowPlayingOnSpotify#87]

**Comment by l3d00m** [comment]
In magicmirror `css/custom.css`:
```css
.NPOS_albumCover {
    width: 80%;
}
```

That might work, I haven't tried it out yet!
